<?php
/** @file
  General functions and constants for validating form submissions.

  @copyright (C) 2013 Alastair Irvine <alastair@plug.org.au>
  @license This project is released under the GNU General Public License
 
  Licence:
      This program is free software; you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation; either version 2 of the License, or (at
      your option) any later version.
 
      See http://www.gnu.org/licenses/gpl-2.0.html for more information.
 
      You can find the complete text of the GPLv2 in the file
      /usr/share/common-licenses/GPL-2 on Debian systems.
*/

  define('PHONE_NUMBER_REGEX', '/^\+?[0-9() ext-]+$/');
?>
