<?php
# TO-DO: 

namespace WPL\MySQL;

class Helper
{
    static $ERROR_DESCRIPTIONS = [
        MySqlError::ER_HASHCHK => "hashchk", // 1000
        MySqlError::ER_NISAMCHK => "isamchk", // 1001
        MySqlError::ER_NO => "NO", // 1002
        MySqlError::ER_YES => "YES", // 1003
        MySqlError::ER_CANT_CREATE_FILE => "Can't create file", // 1004
        MySqlError::ER_CANT_CREATE_TABLE => "Can't create table", // 1005
        MySqlError::ER_CANT_CREATE_DB => "Can't create database", // 1006
        MySqlError::ER_DB_CREATE_EXISTS => "Can't create database as it already exists", // 1007
        MySqlError::ER_DB_DROP_EXISTS => "Can't drop database as it doesn't exist", // 1008
        MySqlError::ER_DB_DROP_DELETE => "Error dropping database (can't delete file)", // 1009
        MySqlError::ER_DB_DROP_RMDIR => "Error dropping database (can't rmdir directory)", // 1010
        MySqlError::ER_CANT_DELETE_FILE => "Error deleting file", // 1011
        MySqlError::ER_CANT_FIND_SYSTEM_REC => "Can't read record in system table", // 1012
        MySqlError::ER_CANT_GET_STAT => "Can't get status of file", // 1013
        MySqlError::ER_CANT_GET_WD => "Can't get working directory", // 1014
        MySqlError::ER_CANT_LOCK => "Can't lock file", // 1015
        MySqlError::ER_CANT_OPEN_FILE => "Can't open file", // 1016
        MySqlError::ER_FILE_NOT_FOUND => "Can't find file as it doesn't exist", // 1017
        MySqlError::ER_CANT_READ_DIR => "Can't read dir", // 1018
        MySqlError::ER_CANT_SET_WD => "Can't change dir", // 1019
        MySqlError::ER_CHECKREAD => "Record has changed since last read", // 1020
        MySqlError::ER_DISK_FULL => "Disk full", // 1021
        MySqlError::ER_DUP_KEY => "Can't write, duplicate key in table", // 1022
        MySqlError::ER_ERROR_ON_CLOSE => "Error on close of file", // 1023
        MySqlError::ER_ERROR_ON_READ => "Error reading file", // 1024
        MySqlError::ER_ERROR_ON_RENAME => "Error on rename of file", // 1025
        MySqlError::ER_ERROR_ON_WRITE => "Error writing file", // 1026
        MySqlError::ER_FILE_USED => "File is locked against change", // 1027
        MySqlError::ER_FILSORT_ABORT => "Sort aborted", // 1028
        MySqlError::ER_FORM_NOT_FOUND => "View doesn't exist", // 1029
        MySqlError::ER_GET_ERRNO => "Got error from table handler", // 1030
        MySqlError::ER_ILLEGAL_HA => "Table handler doesn't have this option", // 1031
        MySqlError::ER_KEY_NOT_FOUND => "Can't find record", // 1032
        MySqlError::ER_NOT_FORM_FILE => "Incorrect information in form file", // 1033
        MySqlError::ER_NOT_KEYFILE => "Incorrect key file for table", // 1034
        MySqlError::ER_OLD_KEYFILE => "Old key file for table", // 1035
        MySqlError::ER_OPEN_AS_READONLY => "Table is read only", // 1036
        MySqlError::ER_OUTOFMEMORY => "Out of memory", // 1037
        MySqlError::ER_OUT_OF_SORTMEMORY => "Out of sort memory. Increase daemon sort buffer size", // 1038
        MySqlError::ER_UNEXPECTED_EOF => "Unexpected eof found when reading file", // 1039
        MySqlError::ER_CON_COUNT_ERROR => "Too many connections", // 1040
        MySqlError::ER_OUT_OF_RESOURCES => "Out of memory", // 1041
        MySqlError::ER_BAD_HOST_ERROR => "Can't get hostname for your address", // 1042
        MySqlError::ER_HANDSHAKE_ERROR => "Bad handshake", // 1043
        MySqlError::ER_DBACCESS_DENIED_ERROR => "Access denied for user to database", // 1044
        MySqlError::ER_ACCESS_DENIED_ERROR => "Access denied for user to server", // 1045
        MySqlError::ER_NO_DB_ERROR => "No Database Selected", // 1046
        MySqlError::ER_UNKNOWN_COM_ERROR => "Unknown command", // 1047
        MySqlError::ER_BAD_NULL_ERROR => "Column cannot be null", // 1048
        MySqlError::ER_BAD_DB_ERROR => "Unknown database", // 1049
        MySqlError::ER_TABLE_EXISTS_ERROR => "Table already exists", // 1050
        MySqlError::ER_BAD_TABLE_ERROR => "Unknown table", // 1051
        MySqlError::ER_NON_UNIQ_ERROR => "Column: is ambiguous", // 1052
        MySqlError::ER_SERVER_SHUTDOWN => "Server shutdown in progress", // 1053
        MySqlError::ER_BAD_FIELD_ERROR => "Unknown column", // 1054
        MySqlError::ER_WRONG_FIELD_WITH_GROUP => "Field isn't in GROUP BY", // 1055
        MySqlError::ER_WRONG_GROUP_FIELD => "Can't group on field", // 1056
        MySqlError::ER_WRONG_SUM_SELECT => "Statement has sum functions and columns in same statement", // 1057
        MySqlError::ER_WRONG_VALUE_COUNT => "Column count doesn't match value count", // 1058
        MySqlError::ER_TOO_LONG_IDENT => "Identifier name is too long", // 1059
        MySqlError::ER_DUP_FIELDNAME => "Duplicate column name", // 1060
        MySqlError::ER_DUP_KEYNAME => "Duplicate key name", // 1061
        MySqlError::ER_DUP_ENTRY => "Duplicate entry", // 1062
        MySqlError::ER_WRONG_FIELD_SPEC => "Incorrect column specifier", // 1063
        MySqlError::ER_PARSE_ERROR => "Parse error", // 1064
        MySqlError::ER_EMPTY_QUERY => "Query was empty", // 1065
        MySqlError::ER_NONUNIQ_TABLE => "Not unique table/alias", // 1066
        MySqlError::ER_INVALID_DEFAULT => "Invalid default value", // 1067
        MySqlError::ER_MULTIPLE_PRI_KEY => "Multiple primary key defined", // 1068
        MySqlError::ER_TOO_MANY_KEYS => "Too many keys specified", // 1069
        MySqlError::ER_TOO_MANY_KEY_PARTS => "Too many key parts specified", // 1070
        MySqlError::ER_TOO_LONG_KEY => "Specified key was too long", // 1071
        MySqlError::ER_KEY_COLUMN_DOES_NOT_EXITS => "Key column doesn't exist in table", // 1072
        MySqlError::ER_BLOB_USED_AS_KEY => "BLOB column can't be used in key specification with the used table type", // 1073
        MySqlError::ER_TOO_BIG_FIELDLENGTH => "Column length is too big", // 1074
        MySqlError::ER_WRONG_AUTO_KEY => "Incorrect table definition; There can only be one auto column and it must be defined as a key", // 1075
        MySqlError::ER_READY => "Server ready for connections", // 1076
        MySqlError::ER_NORMAL_SHUTDOWN => "Normal shutdown", // 1077
        MySqlError::ER_GOT_SIGNAL => "Got fatal signal. Aborting!", // 1078
        MySqlError::ER_SHUTDOWN_COMPLETE => "Shutdown Complete", // 1079
        MySqlError::ER_FORCING_CLOSE => "Forcing close of thread", // 1080
        MySqlError::ER_IPSOCK_ERROR => "Can't create IP socket", // 1081
        MySqlError::ER_NO_SUCH_INDEX => "Table has no index like the one used in CREATE INDEX", // 1082
        MySqlError::ER_WRONG_FIELD_TERMINATORS => "Field separator argument is not what is expected. Check the manual", // 1083
        MySqlError::ER_BLOBS_AND_NO_TERMINATED => "You can't use fixed rowlength with BLOBs. Please use 'fields terminated by'.", // 1084
        MySqlError::ER_TEXTFILE_NOT_READABLE => "File must be in the database directory or be readable by all", // 1085
        MySqlError::ER_FILE_EXISTS_ERROR => "File already exists", // 1086
        MySqlError::ER_LOAD_INFO => "Informational message", // 1087
        MySqlError::ER_ALTER_INFO => "Informational message for ALTER", // 1088
        MySqlError::ER_WRONG_SUB_KEY => "Incorrect sub part key.", // 1089
        MySqlError::ER_CANT_REMOVE_ALL_FIELDS => "You can't delete all columns with ALTER TABLE. Use DROP TABLE instead", // 1090
        MySqlError::ER_CANT_DROP_FIELD_OR_KEY => "Can't DROP column/key", // 1091
        MySqlError::ER_INSERT_INFO => "Informational message for INSERT", // 1092
        MySqlError::ER_INSERT_TABLE_USED => "INSERT TABLE isn't allowed in FROM table list", // 1093
        MySqlError::ER_NO_SUCH_THREAD => "Unknown thread", // 1094
        MySqlError::ER_KILL_DENIED_ERROR => "You are not owner of thread", // 1095
        MySqlError::ER_NO_TABLES_USED => "No tables used", // 1096
        MySqlError::ER_TOO_BIG_SET => "Too many strings with SET", // 1097
        MySqlError::ER_NO_UNIQUE_LOGFILE => "Can't generate a unique log-filename", // 1098
        MySqlError::ER_TABLE_NOT_LOCKED_FOR_WRITE => "Table was locked with a READ lock and can't be updated", // 1099
        MySqlError::ER_TABLE_NOT_LOCKED => "Table was not locked with LOCK TABLES", // 1100
        MySqlError::ER_BLOB_CANT_HAVE_DEFAULT => "BLOB column can't have a default value", // 1101
        MySqlError::ER_WRONG_DB_NAME => "Incorrect database name", // 1102
        MySqlError::ER_WRONG_TABLE_NAME => "Incorrect table name", // 1103
        MySqlError::ER_TOO_BIG_SELECT => "The SELECT would examine too many records and probably take a very long time. Check your WHERE and use SET OPTION SQL_BIG_SELECTS=1 if the SELECT is ok", // 1104
        MySqlError::ER_UNKNOWN_ERROR => "Unknown error", // 1105
        MySqlError::ER_UNKNOWN_PROCEDURE => "Unknown procedure", // 1106
        MySqlError::ER_WRONG_PARAMCOUNT_TO_PROCEDURE => "Incorrect parameter count to procedure", // 1107
        MySqlError::ER_WRONG_PARAMETERS_TO_PROCEDURE => "Incorrect parameters to procedure", // 1108
        MySqlError::ER_UNKNOWN_TABLE => "Unknown table", // 1109
        MySqlError::ER_FIELD_SPECIFIED_TWICE => "Column specified twice", // 1110
        MySqlError::ER_INVALID_GROUP_FUNC_USE => "Invalid use of group function", // 1111
        MySqlError::ER_UNSUPPORTED_EXTENSION => "Table uses an extension that doesn't exist in this MySQL version", // 1112
        MySqlError::ER_TABLE_MUST_HAVE_COLUMNS => "A table must have at least 1 column", // 1113
        MySqlError::ER_RECORD_FILE_FULL => "The table is full", // 1114
        MySqlError::ER_UNKNOWN_CHARACTER_SET => "Unknown character set", // 1115
        MySqlError::ER_TOO_MANY_TABLES => "Too many tables", // 1116
        MySqlError::ER_TOO_MANY_FIELDS => "Too many columns", // 1117
        MySqlError::ER_TOO_BIG_ROWSIZE => "Too big row size", // 1118
        MySqlError::ER_STACK_OVERRUN => "Thread stack overrun", // 1119
        MySqlError::ER_WRONG_OUTER_JOIN => "Cross dependency found in OUTER JOIN", // 1120
        MySqlError::ER_NULL_COLUMN_IN_INDEX => "Column is used with UNIQUE or INDEX but is not defined as NOT NULL", // 1121
        MySqlError::ER_CANT_FIND_UDF => "Can't load function", // 1122
        MySqlError::ER_CANT_INITIALIZE_UDF => "Can't initialize function", // 1123
        MySqlError::ER_UDF_NO_PATHS => "No paths allowed for shared library", // 1124
        MySqlError::ER_UDF_EXISTS => "Function already exist", // 1125
        MySqlError::ER_CANT_OPEN_LIBRARY => "Can't open shared library", // 1126
        MySqlError::ER_CANT_FIND_DL_ENTRY => "Can't find function in library", // 1127
        MySqlError::ER_FUNCTION_NOT_DEFINED => "Function is not defined", // 1128
        MySqlError::ER_HOST_IS_BLOCKED => "Host is blocked because of many connection errors", // 1129
        MySqlError::ER_HOST_NOT_PRIVILEGED => "Host is not allowed to connect to this MySQL server", // 1130
        MySqlError::ER_PASSWORD_ANONYMOUS_USER => "You are using MySQL as an anonymous users and anonymous users are not allowed to change passwords", // 1131
        MySqlError::ER_PASSWORD_NOT_ALLOWED => "You must have privileges to update tables in the mysql database to be able to change passwords for others", // 1132
        MySqlError::ER_PASSWORD_NO_MATCH => "Can't find any matching row in the user table", // 1133
        MySqlError::ER_UPDATE_INFO => "Informational message for UPDATE", // 1134
        MySqlError::ER_CANT_CREATE_THREAD => "Can't create a new thread", // 1135
        MySqlError::ER_WRONG_VALUE_COUNT_ON_ROW => "Column count doesn't match value count", // 1136
        MySqlError::ER_CANT_REOPEN_TABLE => "Can't reopen table", // 1137
        MySqlError::ER_INVALID_USE_OF_NULL => "Invalid use of NULL value", // 1138
        MySqlError::ER_REGEXP_ERROR => "Got error from regexp", // 1139
        MySqlError::ER_MIX_OF_GROUP_FUNC_AND_FIELDS => "Mixing of GROUP columns (MIN(),MAX(),COUNT()...) with no GROUP columns is illegal if there is no GROUP BY clause", // 1140
        MySqlError::ER_NONEXISTING_GRANT => "There is no such grant defined for user+host", // 1141
        MySqlError::ER_TABLEACCESS_DENIED_ERROR => "Command denied to user for table", // 1142
        MySqlError::ER_COLUMNACCESS_DENIED_ERROR => "Command denied to user for column", // 1143
        MySqlError::ER_ILLEGAL_GRANT_FOR_TABLE => "Illegal GRANT/REVOKE command. Please consult the manual which privileges can be used.", // 1144
        MySqlError::ER_GRANT_WRONG_HOST_OR_USER => "The host or user argument to GRANT is too long", // 1145
        MySqlError::ER_NO_SUCH_TABLE => "Table doesn't exist", // 1146
        MySqlError::ER_NONEXISTING_TABLE_GRANT => "There is no such grant defined for user+host on table", // 1147
        MySqlError::ER_NOT_ALLOWED_COMMAND => "The used command is not allowed with this MySQL version", // 1148
        MySqlError::ER_SYNTAX_ERROR => "You have an error in your SQL syntax.  Check the manual that corresponds to your MySQL server version for the right syntax to use", // 1149
        MySqlError::ER_DELAYED_CANT_CHANGE_LOCK => "Delayed insert thread couldn't get requested lock for table", // 1150
        MySqlError::ER_TOO_MANY_DELAYED_THREADS => "Too many delayed threads in use", // 1151
        MySqlError::ER_ABORTING_CONNECTION => "Aborted connection to db", // 1152
        MySqlError::ER_NET_PACKET_TOO_LARGE => "Got a packet bigger than 'max_allowed_packet'", // 1153
        MySqlError::ER_NET_READ_ERROR_FROM_PIPE => "Got a read error from the connection pipe", // 1154
        MySqlError::ER_NET_FCNTL_ERROR => "Got an error from fcntl()", // 1155
        MySqlError::ER_NET_PACKETS_OUT_OF_ORDER => "Got packets out of order", // 1156
        MySqlError::ER_NET_UNCOMPRESS_ERROR => "Couldn't uncompress communication packet", // 1157
        MySqlError::ER_NET_READ_ERROR => "Got an error reading communication packets", // 1158
        MySqlError::ER_NET_READ_INTERRUPTED => "Got timeout reading communication packets", // 1159
        MySqlError::ER_NET_ERROR_ON_WRITE => "Got an error writing communication packets", // 1160
        MySqlError::ER_NET_WRITE_INTERRUPTED => "Got timeout writing communication packets", // 1161
        MySqlError::ER_TOO_LONG_STRING => "Result string is longer than max_allowed_packet", // 1162
        MySqlError::ER_TABLE_CANT_HANDLE_BLOB => "The used table type doesn't support BLOB                                                                                                                                                TEXT columns", // 1163
        MySqlError::ER_TABLE_CANT_HANDLE_AUTO_INCREMENT => "The used table type doesn't support AUTO_INCREMENT columns", // 1164
        MySqlError::ER_DELAYED_INSERT_TABLE_LOCKED => "INSERT DELAYED can't be used with locked table", // 1165
        MySqlError::ER_WRONG_COLUMN_NAME => "Incorrect column name", // 1166
        MySqlError::ER_WRONG_KEY_COLUMN => "The used table handler can't index column", // 1167
        MySqlError::ER_WRONG_MRG_TABLE => "All tables in the MERGE table are not identically defined", // 1168
        MySqlError::ER_DUP_UNIQUE => "Can't write, because of unique constraint, to table", // 1169
        MySqlError::ER_BLOB_KEY_WITHOUT_LENGTH => "BLOB column used in key specification without a key length", // 1170
        MySqlError::ER_PRIMARY_CANT_HAVE_NULL => "All parts of a PRIMARY KEY must be NOT NULL;  If you need NULL in a key, use UNIQUE instead", // 1171
        MySqlError::ER_TOO_MANY_ROWS => "Result consisted of more than one row", // 1172
        MySqlError::ER_REQUIRES_PRIMARY_KEY => "This table type requires a primary key", // 1173
        MySqlError::ER_NO_RAID_COMPILED => "This version of MySQL is not compiled with RAID support", // 1174
        MySqlError::ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE => "You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column", // 1175
        MySqlError::ER_KEY_DOES_NOT_EXITS => "Key doesn't exist in table", // 1176
        MySqlError::ER_CHECK_NO_SUCH_TABLE => "Can't open table", // 1177
        MySqlError::ER_CHECK_NOT_IMPLEMENTED => "The handler for the table doesn't support operation", // 1178
        MySqlError::ER_CANT_DO_THIS_DURING_AN_TRANSACTION => "You are not allowed to execute this command in a transaction", // 1179
        MySqlError::ER_ERROR_DURING_COMMIT => "Got error during COMMIT", // 1180
        MySqlError::ER_ERROR_DURING_ROLLBACK => "Got error during ROLLBACK", // 1181
        MySqlError::ER_ERROR_DURING_FLUSH_LOGS => "Got error during FLUSH_LOGS", // 1182
        MySqlError::ER_ERROR_DURING_CHECKPOINT => "Got error during CHECKPOINT", // 1183
        MySqlError::ER_NEW_ABORTING_CONNECTION => "Aborted connection to db", // 1184
        MySqlError::ER_DUMP_NOT_IMPLEMENTED => "The handler for the table does not support binary table dump", // 1185
        MySqlError::ER_FLUSH_MASTER_BINLOG_CLOSED => "Binlog closed, cannot RESET MASTER", // 1186
        MySqlError::ER_INDEX_REBUILD => "Failed rebuilding the index of dumped table", // 1187
        MySqlError::ER_MASTER => "Error from master", // 1188
        MySqlError::ER_MASTER_NET_READ => "Net error reading from master", // 1189
        MySqlError::ER_MASTER_NET_WRITE => "Net error writing to master", // 1190
        MySqlError::ER_FT_MATCHING_KEY_NOT_FOUND => "Can't find FULLTEXT index matching the column list", // 1191
        MySqlError::ER_LOCK_OR_ACTIVE_TRANSACTION => "Can't execute the given command because you have active locked tables or an active transaction", // 1192
        MySqlError::ER_UNKNOWN_SYSTEM_VARIABLE => "Unknown system variable", // 1193
        MySqlError::ER_CRASHED_ON_USAGE => "Table is marked as crashed and should be repaired", // 1194
        MySqlError::ER_CRASHED_ON_REPAIR => "Table is marked as crashed and last (automatic?) repair failed", // 1195
        MySqlError::ER_WARNING_NOT_COMPLETE_ROLLBACK => "Warning:  Some non-transactional changed tables couldn't be rolled back", // 1196
        MySqlError::ER_TRANS_CACHE_FULL => "Multi-statement transaction required more than 'max_binlog_cache_size' bytes of storage. Increase this mysqld variable and try again',", // 1197
        MySqlError::ER_SLAVE_MUST_STOP => "This operation cannot be performed with a running slave, run SLAVE STOP first", // 1198
        MySqlError::ER_SLAVE_NOT_RUNNING => "This operation requires a running slave, configure slave and do SLAVE START", // 1199
        MySqlError::ER_BAD_SLAVE => "The server is not configured as slave, fix in config file or with CHANGE MASTER TO", // 1200
        MySqlError::ER_MASTER_INFO => "Could not initialize master info structure, check permisions on master.info", // 1201
        MySqlError::ER_SLAVE_THREAD => "Could not create slave thread, check system resources", // 1202
        MySqlError::ER_TOO_MANY_USER_CONNECTIONS => "User has already more than 'max_user_connections' active connections", // 1203
        MySqlError::ER_SET_CONSTANTS_ONLY => "You may only use constant expressions with SET", // 1204
        MySqlError::ER_LOCK_WAIT_TIMEOUT => "Lock wait timeout exceeded; Try restarting transaction", // 1205
        MySqlError::ER_LOCK_TABLE_FULL => "The total number of locks exceeds the lock table size", // 1206
        MySqlError::ER_READ_ONLY_TRANSACTION => "Update locks cannot be acquired during a READ UNCOMMITTED transaction", // 1207
        MySqlError::ER_DROP_DB_WITH_READ_LOCK => "DROP DATABASE not allowed while thread is holding global read lock", // 1208
        MySqlError::ER_CREATE_DB_WITH_READ_LOCK => "CREATE DATABASE not allowed while thread is holding global read lock", // 1209
        MySqlError::ER_WRONG_ARGUMENTS => "Wrong arguments", // 1210
        MySqlError::ER_NO_PERMISSION_TO_CREATE_USER => "Current user is not allowed to create new users", // 1211
        MySqlError::ER_UNION_TABLES_IN_DIFFERENT_DIR => "Incorrect table definition; All MERGE tables must be in the same database", // 1212
        MySqlError::ER_LOCK_DEADLOCK => "Deadlock found when trying to get lock; Try restarting transaction", // 1213
        MySqlError::ER_TABLE_CANT_HANDLE_FULLTEXT => "The used table type doesn't support FULLTEXT indexes", // 1214
        MySqlError::ER_CANNOT_ADD_FOREIGN => "Cannot add foreign key constraint", // 1215
        MySqlError::ER_NO_REFERENCED_ROW => "Cannot add a child row: a foreign key constraint fails", // 1216
        MySqlError::ER_ROW_IS_REFERENCED => "Cannot delete a parent row: a foreign key constraint fails", // 1217
        MySqlError::ER_CONNECT_TO_MASTER => "Error connecting to master", // 1218
        MySqlError::ER_QUERY_ON_MASTER => "Error running query on master", // 1219
        MySqlError::ER_ERROR_WHEN_EXECUTING_COMMAND => "Error when executing command", // 1220
        MySqlError::ER_WRONG_USAGE => "Syntax error: Wrong usage", // 1221
        MySqlError::ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT => "The used SELECT statements have a different number of columns", // 1222
        MySqlError::ER_CANT_UPDATE_WITH_READLOCK => "Can't execute the query because you have a conflicting read lock", // 1223
        MySqlError::ER_MIXING_NOT_ALLOWED => "Mixing of transactional and non-transactional tables is disabled", // 1224
        MySqlError::ER_DUP_ARGUMENT => "Option used twice in statement", // 1225
        MySqlError::ER_USER_LIMIT_REACHED => "User has exceeded a resource limit", // 1226
        MySqlError::ER_SPECIFIC_ACCESS_DENIED_ERROR => "Access denied due to missing privilege", // 1227
        MySqlError::ER_LOCAL_VARIABLE => "Variable is a LOCAL variable and can't be used with SET GLOBAL", // 1228
        MySqlError::ER_GLOBAL_VARIABLE => "Variable is a GLOBAL variable and should be set with SET GLOBAL", // 1229
        MySqlError::ER_NO_DEFAULT => "Variable doesn't have a default value", // 1230
        MySqlError::ER_WRONG_VALUE_FOR_VAR => "Variable can't be set to that value", // 1231
        MySqlError::ER_WRONG_TYPE_FOR_VAR => "Wrong argument type for variable", // 1232
        MySqlError::ER_VAR_CANT_BE_READ => "Variable can only be set, not read", // 1233
        MySqlError::ER_CANT_USE_OPTION_HERE => "Incorrect usage/placement of option", // 1234
        MySqlError::ER_NOT_SUPPORTED_YET => "This version of MySQL doesn't yet support operation", // 1235
        MySqlError::ER_MASTER_FATAL_ERROR_READING_BINLOG => "Got fatal error from master when reading data from binary log", // 1236
        MySqlError::ER_SLAVE_IGNORED_TABLE => "Slave SQL thread ignored the query because of replicate-*-table rules", // 1237
        MySqlError::ER_INCORRECT_GLOBAL_LOCAL_VAR => "Variable is a incorrect kind of variable", // 1238
        MySqlError::ER_WRONG_FK_DEF => "Incorrect foreign key definition", // 1239
        MySqlError::ER_KEY_REF_DO_NOT_MATCH_TABLE_REF => "Key reference and table reference don't match", // 1240
        MySqlError::ER_OPERAND_COLUMNS => "Operand should contain N column(s)", // 1241
        MySqlError::ER_SUBQUERY_NO_1_ROW => "Subquery returns more than 1 row", // 1242
        MySqlError::ER_UNKNOWN_STMT_HANDLER => "Unknown prepared statement handler", // 1243
        MySqlError::ER_CORRUPT_HELP_DB => "Help database is corrupt or does not exist", // 1244
        MySqlError::ER_AUTO_CONVERT => "Error converting column", // 1246
        MySqlError::ER_ILLEGAL_REFERENCE => "Reference not supported", // 1247
        MySqlError::ER_DERIVED_MUST_HAVE_ALIAS => "Every derived table must have its own alias", // 1248
        MySqlError::ER_SELECT_REDUCED => "Select was reduced during optimization", // 1249
        MySqlError::ER_TABLENAME_NOT_ALLOWED_HERE => "A table from one of the SELECTs cannot be used", // 1250
        MySqlError::ER_NOT_SUPPORTED_AUTH_MODE => "Client does not support authentication protocol requested by server; consider upgrading MySQL client", // 1251
        MySqlError::ER_SPATIAL_CANT_HAVE_NULL => "All parts of a SPATIAL index must be NOT NULL", // 1252
        MySqlError::ER_COLLATION_CHARSET_MISMATCH => "COLLATION is not valid for CHARACTER SET", // 1253
        MySqlError::ER_TOO_BIG_FOR_UNCOMPRESS => "Uncompressed data size too large", // 1256
        MySqlError::ER_ZLIB_Z_MEM_ERROR => "ZLIB: Not enough memory", // 1257
        MySqlError::ER_ZLIB_Z_BUF_ERROR => "ZLIB: Not enough room in the output buffer (probably, length of uncompressed data was corrupted)", // 1258
        MySqlError::ER_ZLIB_Z_DATA_ERROR => "ZLIB: Input data corrupted", // 1259
        MySqlError::ER_CUT_VALUE_GROUP_CONCAT => "Row was cut by GROUP_CONCAT()", // 1260
        MySqlError::ER_WARN_TOO_FEW_RECORDS => "Row doesn't contain data for all columns", // 1261
        MySqlError::ER_WARN_TOO_MANY_RECORDS => "Row was truncated; it contained more data than there were input columns", // 1262
        MySqlError::ER_WARN_NULL_TO_NOTNULL => "Column set to default value; NULL supplied to NOT NULL column", // 1263
        MySqlError::ER_WARN_DATA_OUT_OF_RANGE => "Out of range value for column", // 1264
        MySqlError::WARN_DATA_TRUNCATED => "Data truncated for column", // 1265
        MySqlError::ER_WARN_USING_OTHER_HANDLER => "Using different storage engine for this table", // 1266
        MySqlError::ER_CANT_AGGREGATE_2COLLATIONS => "Illegal mix of collations for operation", // 1267
        MySqlError::ER_REVOKE_GRANTS => "Can't revoke all privileges for one or more of the requested users", // 1269
        MySqlError::ER_CANT_AGGREGATE_3COLLATIONS => "Illegal mix of collations for operation", // 1270
        MySqlError::ER_CANT_AGGREGATE_NCOLLATIONS => "Illegal mix of collations for operation", // 1271
        MySqlError::ER_VARIABLE_IS_NOT_STRUCT => "Variable is not a variable component (can't be used as XXXX.variable_name)", // 1272
        MySqlError::ER_UNKNOWN_COLLATION => "Unknown collation", // 1273
        MySqlError::ER_SLAVE_IGNORED_SSL_PARAMS => "SSL parameters in CHANGE MASTER are ignored because this MySQL slave was compiled without SSL support; they can be used later if MySQL slave with SSL is started", // 1274
        MySqlError::ER_SERVER_IS_IN_SECURE_AUTH_MODE => "Server is running in --secure-auth mode, but user has a password in the old format; please change the password to the new format", // 1275
        MySqlError::ER_WARN_FIELD_RESOLVED => "Field or reference of SELECT was resolved in another SELECT", // 1276
        MySqlError::ER_BAD_SLAVE_UNTIL_COND => "Incorrect parameter or combination of parameters for START SLAVE UNTIL", // 1277
        MySqlError::ER_MISSING_SKIP_SLAVE => "It is recommended to use --skip-replica-start when doing step-by-step replication with START SLAVE UNTIL; otherwise, you will get problems if you get an unexpected slave's mysqld restart", // 1278
        MySqlError::ER_UNTIL_COND_IGNORED => "SQL thread is not to be started so UNTIL options are ignored", // 1279
        MySqlError::ER_WRONG_NAME_FOR_INDEX => "Incorrect index name", // 1280
        MySqlError::ER_WRONG_NAME_FOR_CATALOG => "Incorrect catalog name", // 1281
        MySqlError::ER_WARN_QC_RESIZE => "Query cache failed to set size", // 1282
        MySqlError::ER_BAD_FT_COLUMN => "A column cannot be part of FULLTEXT index", // 1283
        MySqlError::ER_UNKNOWN_KEY_CACHE => "Unknown key cache", // 1284
        MySqlError::ER_WARN_HOSTNAME_WONT_WORK => "MySQL is started in --skip-name-resolve mode; you must restart it without this switch for this grant to work", // 1285
        MySqlError::ER_UNKNOWN_STORAGE_ENGINE => "Unknown storage engine", // 1286
        MySqlError::ER_WARN_DEPRECATED_SYNTAX => "Syntax is deprecated and will be removed in a future release.", // 1287
        MySqlError::ER_NON_UPDATABLE_TABLE => "The target table is not updatable", // 1288
        MySqlError::ER_FEATURE_DISABLED => "This feature is disabled", // 1289
        MySqlError::ER_OPTION_PREVENTS_STATEMENT => "The MySQL server is running with an option that means it cannot execute this statement", // 1290
        MySqlError::ER_DUPLICATED_VALUE_IN_TYPE => "A column has duplicated value", // 1291
        MySqlError::ER_TRUNCATED_WRONG_VALUE => "Truncated incorrect value", // 1292
        MySqlError::ER_INVALID_ON_UPDATE => "Invalid ON UPDATE clause for column", // 1294
        MySqlError::ER_UNSUPPORTED_PS => "This command is not supported in the prepared statement protocol yet", // 1295
        MySqlError::ER_GET_ERRMSG => "Got error from underlying subsystem", // 1296
        MySqlError::ER_GET_TEMPORARY_ERRMSG => "Got temporary error from underlying subsystem", // 1297
        MySqlError::ER_UNKNOWN_TIME_ZONE => "Unknown or incorrect time zone", // 1298
        MySqlError::ER_WARN_INVALID_TIMESTAMP => "Invalid TIMESTAMP value", // 1299
        MySqlError::ER_INVALID_CHARACTER_STRING => "Invalid character string", // 1300
        MySqlError::ER_WARN_ALLOWED_PACKET_OVERFLOWED => "Result was larger than max_allowed_packet and was truncated", // 1301
        MySqlError::ER_CONFLICTING_DECLARATIONS => "Conflicting declarations", // 1302
        MySqlError::ER_SP_NO_RECURSIVE_CREATE => "Can't create entity from within another stored routine", // 1303
        MySqlError::ER_SP_ALREADY_EXISTS => "Entity already exists", // 1304
        MySqlError::ER_SP_DOES_NOT_EXIST => "Entity does not exist", // 1305
        MySqlError::ER_SP_DROP_FAILED => "Failed to DROP entity", // 1306
        MySqlError::ER_SP_STORE_FAILED => "Failed to CREATE entity", // 1307
        MySqlError::ER_SP_LILABEL_MISMATCH => "Error due to no matching label", // 1308
        MySqlError::ER_SP_LABEL_REDEFINE => "Redefining label", // 1309
        MySqlError::ER_SP_LABEL_MISMATCH => "End-label is missing match", // 1310
        MySqlError::ER_SP_UNINIT_VAR => "Referring to uninitialized variable", // 1311
        MySqlError::ER_SP_BADSELECT => "PROCEDURE can't return a result set in the given context", // 1312
        MySqlError::ER_SP_BADRETURN => "RETURN is only allowed in a FUNCTION", // 1313
        MySqlError::ER_SP_BADSTATEMENT => "Statement is not allowed in stored procedures", // 1314
        MySqlError::ER_UPDATE_LOG_DEPRECATED_IGNORED => "The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been ignored.", // 1315
        MySqlError::ER_UPDATE_LOG_DEPRECATED_TRANSLATED => "The update log is deprecated and replaced by the binary log; SET SQL_LOG_UPDATE has been translated to SET SQL_LOG_BIN.", // 1316
        MySqlError::ER_QUERY_INTERRUPTED => "Query execution was interrupted", // 1317
        MySqlError::ER_SP_WRONG_NO_OF_ARGS => "Incorrect number of arguments", // 1318
        MySqlError::ER_SP_COND_MISMATCH => "Undefined CONDITION", // 1319
        MySqlError::ER_SP_NORETURN => "No RETURN found in FUNCTION", // 1320
        MySqlError::ER_SP_NORETURNEND => "FUNCTION ended without RETURN", // 1321
        MySqlError::ER_SP_BAD_CURSOR_QUERY => "Cursor statement must be a SELECT", // 1322
        MySqlError::ER_SP_BAD_CURSOR_SELECT => "Cursor SELECT must not have INTO", // 1323
        MySqlError::ER_SP_CURSOR_MISMATCH => "Undefined CURSOR", // 1324
        MySqlError::ER_SP_CURSOR_ALREADY_OPEN => "Cursor is already open", // 1325
        MySqlError::ER_SP_CURSOR_NOT_OPEN => "Cursor is not open", // 1326
        MySqlError::ER_SP_UNDECLARED_VAR => "Undeclared variable", // 1327
        MySqlError::ER_SP_WRONG_NO_OF_FETCH_ARGS => "Incorrect number of FETCH variables", // 1328
        MySqlError::ER_SP_FETCH_NO_DATA => "No data - zero rows fetched, selected, or processed", // 1329
        MySqlError::ER_SP_DUP_PARAM => "Duplicate parameter", // 1330
        MySqlError::ER_SP_DUP_VAR => "Duplicate variable", // 1331
        MySqlError::ER_SP_DUP_COND => "Duplicate condition", // 1332
        MySqlError::ER_SP_DUP_CURS => "Duplicate cursor", // 1333
        MySqlError::ER_SP_CANT_ALTER => "Failed to ALTER entity", // 1334
        MySqlError::ER_SP_SUBSELECT_NYI => "Subquery value not supported", // 1335
        MySqlError::ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG => "Statement is not allowed in stored function or trigger", // 1336
        MySqlError::ER_SP_VARCOND_AFTER_CURSHNDLR => "Variable or condition declaration after cursor or handler declaration", // 1337
        MySqlError::ER_SP_CURSOR_AFTER_HANDLER => "Cursor declaration after handler declaration", // 1338
        MySqlError::ER_SP_CASE_NOT_FOUND => "Case not found for CASE statement", // 1339
        MySqlError::ER_FPARSER_TOO_BIG_FILE => "Configuration file is too big", // 1340
        MySqlError::ER_FPARSER_BAD_HEADER => "Malformed file type header", // 1341
        MySqlError::ER_FPARSER_EOF_IN_COMMENT => "Unexpected end of file while parsing comment", // 1342
        MySqlError::ER_FPARSER_ERROR_IN_PARAMETER => "Error while parsing parameter", // 1343
        MySqlError::ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER => "Unexpected end of file while skipping unknown parameter", // 1344
        MySqlError::ER_VIEW_NO_EXPLAIN => "EXPLAIN/SHOW can not be issued; lacking privileges for underlying table", // 1345
        MySqlError::ER_WRONG_OBJECT => "The named object is incorrect for the type of operation attempted on it. It must be an object of the named type.", // 1347
        MySqlError::ER_NONUPDATEABLE_COLUMN => "Column is not updatable", // 1348
        MySqlError::ER_VIEW_SELECT_CLAUSE => "View's SELECT contains a bad clause", // 1350
        MySqlError::ER_VIEW_SELECT_VARIABLE => "View's SELECT contains a variable or parameter", // 1351
        MySqlError::ER_VIEW_SELECT_TMPTABLE => "View's SELECT refers to a temporary table", // 1352
        MySqlError::ER_VIEW_WRONG_LIST => "In definition of view, derived table or common table expression, SELECT list and column names list have different column counts", // 1353
        MySqlError::ER_WARN_VIEW_MERGE => "View merge algorithm can't be used here for now (assumed undefined algorithm)", // 1354
        MySqlError::ER_WARN_VIEW_WITHOUT_KEY => "View being updated does not have complete key of underlying table in it", // 1355
        MySqlError::ER_VIEW_INVALID => "View references invalid table(s) or column(s) or function(s) or definer invoker of view lack rights to use them", // 1356
        MySqlError::ER_SP_NO_DROP_SP => "Can't drop or alter entity from within another stored routine", // 1357
        MySqlError::ER_TRG_ALREADY_EXISTS => "Trigger already exists", // 1359
        MySqlError::ER_TRG_DOES_NOT_EXIST => "Trigger does not exist", // 1360
        MySqlError::ER_TRG_ON_VIEW_OR_TEMP_TABLE => "Trigger's object is view or temporary table", // 1361
        MySqlError::ER_TRG_CANT_CHANGE_ROW => "Updating of row is not allowed in trigger", // 1362
        MySqlError::ER_TRG_NO_SUCH_ROW_IN_TRG => "There is no such row in trigger", // 1363
        MySqlError::ER_NO_DEFAULT_FOR_FIELD => "Field doesn't have a default value", // 1364
        MySqlError::ER_DIVISION_BY_ZERO => "Division by 0", // 1365
        MySqlError::ER_TRUNCATED_WRONG_VALUE_FOR_FIELD => "Incorrect field value", // 1366
        MySqlError::ER_ILLEGAL_VALUE_FOR_TYPE => "Illegal value for type found during parsing", // 1367
        MySqlError::ER_VIEW_NONUPD_CHECK => "CHECK OPTION on non-updatable view", // 1368
        MySqlError::ER_VIEW_CHECK_FAILED => "CHECK OPTION failed", // 1369
        MySqlError::ER_PROCACCESS_DENIED_ERROR => "Command denied to user for this routine", // 1370
        MySqlError::ER_RELAY_LOG_FAIL => "Failed purging old relay logs", // 1371
        MySqlError::ER_UNKNOWN_TARGET_BINLOG => "Target log not found in binlog index", // 1373
        MySqlError::ER_IO_ERR_LOG_INDEX_READ => "I/O error reading log index file", // 1374
        MySqlError::ER_BINLOG_PURGE_PROHIBITED => "Server configuration does not permit binlog purge", // 1375
        MySqlError::ER_FSEEK_FAIL => "Failed on fseek()", // 1376
        MySqlError::ER_BINLOG_PURGE_FATAL_ERR => "Fatal error during log purge", // 1377
        MySqlError::ER_LOG_IN_USE => "A purgeable log is in use, will not purge", // 1378
        MySqlError::ER_LOG_PURGE_UNKNOWN_ERR => "Unknown error during log purge", // 1379
        MySqlError::ER_RELAY_LOG_INIT => "Failed initializing relay log position", // 1380
        MySqlError::ER_NO_BINARY_LOGGING => "You are not using binary logging", // 1381
        MySqlError::ER_RESERVED_SYNTAX => "Syntax is reserved for purposes internal to the MySQL server", // 1382
        MySqlError::ER_PS_MANY_PARAM => "Prepared statement contains too many placeholders", // 1390
        MySqlError::ER_KEY_PART_0 => "Key part length cannot be 0", // 1391
        MySqlError::ER_VIEW_CHECKSUM => "View text checksum failed", // 1392
        MySqlError::ER_VIEW_MULTIUPDATE => "Can not modify more than one base table through a join view", // 1393
        MySqlError::ER_VIEW_NO_INSERT_FIELD_LIST => "Can not insert into join view without fields list", // 1394
        MySqlError::ER_VIEW_DELETE_MERGE_VIEW => "Can not delete from join view", // 1395
        MySqlError::ER_CANNOT_USER => "Operation failed", // 1396
        MySqlError::ER_XAER_NOTA => "XAER_NOTA: Unknown XID", // 1397
        MySqlError::ER_XAER_INVAL => "XAER_INVAL: Invalid arguments (or unsupported command)", // 1398
        MySqlError::ER_XAER_RMFAIL => "XAER_RMFAIL: The command cannot be executed when global transaction is in current state", // 1399
        MySqlError::ER_XAER_OUTSIDE => "XAER_OUTSIDE: Some work is done outside global transaction", // 1400
        MySqlError::ER_XAER_RMERR => "XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency", // 1401
        MySqlError::ER_XA_RBROLLBACK => "XA_RBROLLBACK: Transaction branch was rolled back", // 1402
        MySqlError::ER_NONEXISTING_PROC_GRANT => "There is no such grant defined for user+host on routine", // 1403
        MySqlError::ER_PROC_AUTO_GRANT_FAIL => "Failed to grant EXECUTE and ALTER ROUTINE privileges", // 1404
        MySqlError::ER_PROC_AUTO_REVOKE_FAIL => "Failed to revoke all privileges to dropped routine", // 1405
        MySqlError::ER_DATA_TOO_LONG => "Data too long for column", // 1406
        MySqlError::ER_SP_BAD_SQLSTATE => "Bad SQLSTATE", // 1407
        MySqlError::ER_STARTUP => "Server ready for connections.", // 1408
        MySqlError::ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR => "Can't load value from file with fixed size rows to variable", // 1409
        MySqlError::ER_CANT_CREATE_USER_WITH_GRANT => "You are not allowed to create a user with GRANT", // 1410
        MySqlError::ER_WRONG_VALUE_FOR_TYPE => "Incorrect value for function", // 1411
        MySqlError::ER_TABLE_DEF_CHANGED => "Table definition has changed, please retry transaction", // 1412
        MySqlError::ER_SP_DUP_HANDLER => "Duplicate handler declared in the same block", // 1413
        MySqlError::ER_SP_NOT_VAR_ARG => "OUT or INOUT argument for routine is not a variable or NEW pseudo-variable in BEFORE trigger", // 1414
        MySqlError::ER_SP_NO_RETSET => "Not allowed to return a result set", // 1415
        MySqlError::ER_CANT_CREATE_GEOMETRY_OBJECT => "Cannot get geometry object from data you send to the GEOMETRY field", // 1416
        MySqlError::ER_BINLOG_UNSAFE_ROUTINE => "This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration and binary logging is enabled", // 1418
        MySqlError::ER_BINLOG_CREATE_ROUTINE_NEED_SUPER => "You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)", // 1419
        MySqlError::ER_STMT_HAS_NO_OPEN_CURSOR => "The statement has no open cursor.", // 1421
        MySqlError::ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG => "Explicit or implicit commit is not allowed in stored function or trigger.", // 1422
        MySqlError::ER_NO_DEFAULT_FOR_VIEW_FIELD => "Field of view underlying table doesn't have a default value", // 1423
        MySqlError::ER_SP_NO_RECURSION => "Recursive stored functions and triggers are not allowed.", // 1424
        MySqlError::ER_TOO_BIG_SCALE => "Too big scale specified for column.", // 1425
        MySqlError::ER_TOO_BIG_PRECISION => "Too-big precision specified.", // 1426
        MySqlError::ER_M_BIGGER_THAN_D => "For float(M,D), double(M,D) or decimal(M,D), M must be >= D.", // 1427
        MySqlError::ER_WRONG_LOCK_OF_SYSTEM_TABLE => "You can't combine write-locking of system tables with other tables or lock types", // 1428
        MySqlError::ER_CONNECT_TO_FOREIGN_DATA_SOURCE => "Unable to connect to foreign data source", // 1429
        MySqlError::ER_QUERY_ON_FOREIGN_DATA_SOURCE => "There was a problem processing the query on the foreign data source.", // 1430
        MySqlError::ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST => "The foreign data source you are trying to reference does not exist.", // 1431
        MySqlError::ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE => "Can't create federated table. Incorrect format for data source connection string.", // 1432
        MySqlError::ER_FOREIGN_DATA_STRING_INVALID => "Incorrect format for data source connection string.", // 1433
        MySqlError::ER_TRG_IN_WRONG_SCHEMA => "Trigger in wrong schema", // 1435
        MySqlError::ER_SAND_SECS_USED_TOGETHER => "The option expire_logs_days and binlog_expire_logs_seconds cannot be used together. Please use binlog_expire_logs_seconds to set the expire time (expire_logs_days is deprecated)", // 1436
        MySqlError::ER_REGEXP_STRING_NOT_TERMINATED => "An output string could not be zero-terminated because the length exceeds the buffer capacity.", // 3684
        MySqlError::ER_REGEXP_BUFFER_OVERFLOW => "The result string is larger than the result buffer.", // 3684
        MySqlError::ER_REGEXP_ILLEGAL_ARGUMENT => "Illegal argument to a regular expression.", // 3685
        MySqlError::ER_REGEXP_INDEX_OUTOFBOUNDS_ERROR => "Index out of bounds in regular expression search.", // 3686
        MySqlError::ER_REGEXP_INTERNAL_ERROR => "Internal error in the regular expression library.", // 3687
        MySqlError::ER_REGEXP_RULE_SYNTAX => "Syntax error in regular expression.", // 3688
        MySqlError::ER_REGEXP_BAD_ESCAPE_SEQUENCE => "Unrecognized escape sequence in regular expression.", // 3689
        MySqlError::ER_REGEXP_UNIMPLEMENTED => "The regular expression contains a feature that is not implemented in this library version.", // 3690
        MySqlError::ER_REGEXP_MISMATCHED_PAREN => "Mismatched parenthesis in regular expression.", // 3691
        MySqlError::ER_REGEXP_BAD_INTERVAL => "Incorrect description of a {min,max} interval.", // 3692
        MySqlError::ER_REGEXP_MAX_LT_MIN => "The maximum is less than the minumum in a {min,max} interval.", // 3693
        MySqlError::ER_REGEXP_INVALID_BACK_REF => "Invalid back-reference in regular expression.", // 3694
        MySqlError::ER_REGEXP_LOOK_BEHIND_LIMIT => "The look-behind assertion exceeds the limit in regular expression.", // 3695
        MySqlError::ER_REGEXP_MISSING_CLOSE_BRACKET => "The regular expression contains an unclosed bracket expression.", // 3696
        MySqlError::ER_REGEXP_INVALID_RANGE => "The regular expression contains an [x-y] character range where x comes after y.", // 3697
        MySqlError::ER_REGEXP_STACK_OVERFLOW => "Overflow in the regular expression backtrack stack.", // 3698
        MySqlError::ER_REGEXP_TIME_OUT => "Timeout exceeded in regular expression match.", // 3699
        MySqlError::ER_REGEXP_PATTERN_TOO_BIG => "SQLSTn attribute error", // 3700
        MySqlError::ER_ENGINE_ATTRIBUTE_NOT_SUPPORTED => "Storage engine does not support ENGINE_ATTRIBUTE.", // 3981
        MySqlError::ER_INVALID_USER_ATTRIBUTE_JSON => "The user attribute must be a valid JSON object", // 3982
        MySqlError::ER_INNODB_REDO_DISABLED => "Cannot perform operation as InnoDB redo logging is disabled. Please retry after enabling redo log with ALTER INSTANCE", // 3983
        MySqlError::ER_INNODB_REDO_ARCHIVING_ENABLED => "Cannot perform operation as InnoDB is archiving redo log. Please retry after stopping redo archive by invoking innodb_redo_log_archive_stop()", // 3984
        MySqlError::ER_MDL_OUT_OF_RESOURCES => "Not enough resources to complete lock request.", // 3985
        MySqlError::ER_IMPLICIT_COMPARISON_FOR_JSON => "Evaluating a JSON value in SQL boolean context does an implicit comparison against JSON integer 0; if this is not what you want, consider converting JSON to a SQL numeric type with JSON_VALUE RETURNING", // 3986
        MySqlError::ER_FUNCTION_DOES_NOT_SUPPORT_CHARACTER_SET => "The function does not support the character set.", // 3987
        MySqlError::ER_IMPOSSIBLE_STRING_CONVERSION => "Collation conversion impossible.", // 3988
        MySqlError::ER_SCHEMA_READ_ONLY => "Schema is in read only mode.", // 3989
        MySqlError::ER_RPL_ASYNC_RECONNECT_GTID_MODE_OFF => "Failed to enable Asynchronous Replication Connection Failover feature. The CHANGE MASTER TO SOURCE_CONNECTION_AUTO_FAILOVER = 1 can only be set when @@GLOBAL.GTID_MODE = ON.", // 3990
        MySqlError::ER_RPL_ASYNC_RECONNECT_AUTO_POSITION_OFF => "Failed to enable Asynchronous Replication Connection Failover feature. The CHANGE MASTER TO SOURCE_CONNECTION_AUTO_FAILOVER = 1 can only be set when MASTER_AUTO_POSITION option of CHANGE MASTER TO is enabled.", // 3991
        MySqlError::ER_DISABLE_GTID_MODE_REQUIRES_ASYNC_RECONNECT_OFF => "The @@GLOBAL.GTID_MODEcannot be changed because Asynchronous Replication Connection Failover is enabled.", // 3992
        MySqlError::ER_DISABLE_AUTO_POSITION_REQUIRES_ASYNC_RECONNECT_OFF => "CHANGE MASTER TO MASTER_AUTO_POSITION = 0 cannot be executed because Asynchronous Replication Connection Failover is enabled.", // 3993
        MySqlError::ER_INVALID_PARAMETER_USE => "Invalid use of parameters.", // 3994
        MySqlError::ER_CHARACTER_SET_MISMATCH => "Character set mismatch.", // 3995
        MySqlError::ER_WARN_VAR_VALUE_CHANGE_NOT_SUPPORTED => "Changing variable not supported on this platform. Falling back to the default.", // 3996
        MySqlError::ER_INVALID_TIME_ZONE_INTERVAL => "Invalid time zone interval.", // 3997
        MySqlError::ER_INVALID_CAST => "Cannot cast value.", // 3998
        MySqlError::ER_HYPERGRAPH_NOT_SUPPORTED_YET => "The hypergraph optimizer does not yet support that.", // 3999
        MySqlError::ER_WARN_HYPERGRAPH_EXPERIMENTAL => "The hypergraph optimizer is highly experimental and is meant for testing only. Do not enable it unless you are a MySQL developer.", // 4000
        MySqlError::ER_DA_NO_ERROR_LOG_PARSER_CONFIGURED => "None of the log-sinks selected with --log-error-services=... provides a log-parser. The server will not be able to make the previous runs' error-logs available in performance_schema.error_log.", // 4001
        MySqlError::ER_DA_ERROR_LOG_TABLE_DISABLED => "None of the log-sinks selected in @@global.log_error_services supports writing to the performance schema. The server will not be able to make the current runs' error events available in performance_schema.error_log. To change this, add a log-sink that supports the performance schema to @@global.log_error_services.", // 4002
        MySqlError::ER_DA_ERROR_LOG_MULTIPLE_FILTERS => "@@global.log_error_services lists more than one log-filter service. This is discouraged as it will make it hard to understand which rule in which filter affected a log-event.", // 4003
        MySqlError::ER_DA_CANT_OPEN_ERROR_LOG => "Could not open file for error logging.", // 4004
        MySqlError::ER_USER_REFERENCED_AS_DEFINER => "User is referenced as a definer account.", // 4005
        MySqlError::ER_CANNOT_USER_REFERENCED_AS_DEFINER => "Operation failed as it is referenced as a definer account.", // 4006
        MySqlError::ER_REGEX_NUMBER_TOO_BIG => "Decimal number in regular expression is too large.", // 4007
        MySqlError::ER_SPVAR_NONINTEGER_TYPE => "Variable has a non-integer based type.", // 4008
        MySqlError::WARN_UNSUPPORTED_ACL_TABLES_READ => "Reads with serializable isolation/SELECT FOR SHARE are not supported for ACL tables.", // 4009
        MySqlError::ER_BINLOG_UNSAFE_ACL_TABLE_READ_IN_DML_DDL => "The statement is unsafe because it updates a table depending on ACL table read operation. As storage engine row locks are skipped for ACL table, it may not have same effect on master and slave.", // 4010
        MySqlError::ER_STOP_REPLICA_MONITOR_IO_THREAD_TIMEOUT => "STOP REPLICA command execution is incomplete: Replica Monitor thread got the stop signal, thread is busy, Monitor thread will stop once the current task is complete.", // 4011
        MySqlError::ER_STARTING_REPLICA_MONITOR_IO_THREAD => "The Replica Monitor thread failed to start.", // 4012
        MySqlError::ER_CANT_USE_ANONYMOUS_TO_GTID_WITH_GTID_MODE_NOT_ON => "Replication cannot start with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = LOCAL|<UUID> as this server uses @@GLOBAL.GTID_MODE <> ON.", // 4013
        MySqlError::ER_CANT_COMBINE_ANONYMOUS_TO_GTID_AND_AUTOPOSITION => "The options ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = LOCAL|<UUID> and MASTER_AUTO_POSITION = 1 cannot be used together.", // 4014
        MySqlError::ER_ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_REQUIRES_GTID_MODE_ON => "CHANGE MASTER TO ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = LOCAL|<UUID> cannot be executed because @@GLOBAL.GTID_MODE <> ON.", // 4015
        MySqlError::ER_SQL_SLAVE_SKIP_COUNTER_USED_WITH_GTID_MODE_ON => "The value of sql_slave_skip_counter will only take effect for channels running with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS <> OFF.", // 4016
        MySqlError::ER_SQL_REPLICA_SKIP_COUNTER_USED_WITH_GTID_MODE_ON => "The value of sql_replica_skip_counter will only take effect for channels running with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS <> OFF.", // 4016
        MySqlError::ER_USING_ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS_AS_LOCAL_OR_UUID => "Using ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS creates limitations on the replication topology - you cannot fail over between downstream and upstream servers. Only use this option if it is not possible to enable GTIDs on the source, for instance, because of lack of permissions. If possible, use the procedure for enabling GTID transactions online instead, as described in the documentation.", // 4017
        MySqlError::ER_CANT_SET_ANONYMOUS_TO_GTID_AND_WAIT_UNTIL_SQL_THD_AFTER_GTIDS => "WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS cannot be used on a channel configured with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = LOCAL|<UUID>", // 4018
        MySqlError::ER_CANT_SET_SQL_AFTER_OR_BEFORE_GTIDS_WITH_ANONYMOUS_TO_GTID => "The SQL_AFTER_GTIDS or SQL_BEFORE_GTIDS clauses for START REPLICA cannot be used when the replication channel is configured with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = LOCAL|<UUID>.", // 4019
        MySqlError::ER_ANONYMOUS_TO_GTID_UUID_SAME_AS_GROUP_NAME => "Replication is configured with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = <UUID> where the UUID value is equal to the group_replication_group_name", // 4020
        MySqlError::ER_CANT_USE_SAME_UUID_AS_GROUP_NAME => "CHANGE MASTER TO ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = <UUID> cannot be executed because the UUID value is equal to the group_replication_group_name.", // 4021
        MySqlError::ER_GRP_RPL_RECOVERY_CHANNEL_STILL_RUNNING => "The group_replication_recovery channel is still running, most likely it is waiting for a database/table lock, which is preventing the channel from stopping. Please check database/table locks, including the ones created by backup tools.", // 4022
        MySqlError::ER_INNODB_INVALID_AUTOEXTEND_SIZE_VALUE => "AUTOEXTEND_SIZE invalid.", // 4023
        MySqlError::ER_INNODB_INCOMPATIBLE_WITH_TABLESPACE => "InnoDB: problem when using general tablespaces", // 4024
        MySqlError::ER_INNODB_AUTOEXTEND_SIZE_OUT_OF_RANGE => "AUTOEXTEND_SIZE value out-of-range.", // 4025
        MySqlError::ER_CANNOT_USE_AUTOEXTEND_SIZE_CLAUSE => "AUTOEXTEND_SIZE clause is not valid for this tablespace.", // 4026
        MySqlError::ER_ROLE_GRANTED_TO_ITSELF => "User account is directly or indirectly granted to the role. The GRANT would create a loop.", // 4027
        MySqlError::ER_TABLE_MUST_HAVE_A_VISIBLE_COLUMN => "A table must have at least one visible column.", // 4028
        MySqlError::ER_INNODB_COMPRESSION_FAILURE => "Compression failed.", // 4029
        MySqlError::ER_WARN_ASYNC_CONN_FAILOVER_NETWORK_NAMESPACE => "The parameter network_namespace is reserved for future use. Please use the CHANGE REPLICATION SOURCE command to set channel network_namespace parameter.", // 4030
        MySqlError::ER_CLIENT_INTERACTION_TIMEOUT => "The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.", // 4031
        MySqlError::ER_INVALID_CAST_TO_GEOMETRY => "Invalid cast to geometry.", // 4032
        MySqlError::ER_INVALID_CAST_POLYGON_RING_DIRECTION => "Invalid cast to polygon. A polygon ring is in the wrong direction.", // 4033
        MySqlError::ER_GIS_DIFFERENT_SRIDS_AGGREGATION => "Arguments to function contains geometries with different SRIDs. All geometries must have the same SRID.", // 4034
        MySqlError::ER_RELOAD_KEYRING_FAILURE => "Keyring reload failed. Please check error log for more details.", // 4035
        MySqlError::ER_SDI_GET_KEYS_INVALID_TABLESPACE => "Tablespace is invalid for SDI operations.", // 4036
        MySqlError::ER_CHANGE_RPL_SRC_WRONG_COMPRESSION_ALGORITHM_SIZE => "Value too long for SOURCE_COMPRESSION_ALGORITHMS option for this channel.", // 4037
        MySqlError::ER_WARN_DEPRECATED_TLS_VERSION_FOR_CHANNEL_CLI => "A deprecated TLS version is enabled for this channel. Please use TLSv1.2 or higher.", // 4038
        MySqlError::ER_CANT_USE_SAME_UUID_AS_VIEW_CHANGE_UUID => "CHANGE REPLICATION SOURCE TO ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = <UUID> cannot be executed because the UUID value is equal to the group_replication_view_change_uuid.", // 4039
        MySqlError::ER_ANONYMOUS_TO_GTID_UUID_SAME_AS_VIEW_CHANGE_UUID => "Replication is configured with ASSIGN_GTIDS_TO_ANONYMOUS_TRANSACTIONS = <UUID> where the UUID value is equal to the group_replication_view_change_uuid", // 4040
        MySqlError::ER_GRP_RPL_VIEW_CHANGE_UUID_FAIL_GET_VARIABLE => "Unable to retrieve group_replication_view_change_uuid variable during server checks on replication operations.", // 4041
        MySqlError::ER_WARN_ADUIT_LOG_MAX_SIZE_AND_PRUNE_SECONDS => "Both audit_log_max_size and audit_log_prune_seconds are set to non-zero. audit_log_max_size takes precedence and audit_log_prune_seconds is ignored", // 4042
        MySqlError::ER_WARN_ADUIT_LOG_MAX_SIZE_CLOSE_TO_ROTATE_ON_SIZE => "audit_log_rotate_on_size is not granular enough for the value of audit_log_max_size supplied.", // 4043
        MySqlError::ER_KERBEROS_CREATE_USER => "Create/Alter user has failed, Configured user realm as authentication string is empty, Please make sure to configure authentication string as user realm.", // 4044
        MySqlError::ER_INSTALL_PLUGIN_CONFLICT_CLIENT => "Cannot install plugin due to conflict with an installed plugin.", // 4045
        MySqlError::ER_DA_ERROR_LOG_COMPONENT_FLUSH_FAILED => "Error logging component(s) failed to flush.", // 4046
        MySqlError::ER_WARN_SQL_AFTER_MTS_GAPS_GAP_NOT_CALCULATED => "The until clause SQL_AFTER_MTS_GAPS is being used for this channel when GTID_MODE = ON and SOURCE_AUTO_POSITION=1 meaning the server did not compute internally what gaps may exist in the relay log transaction execution.", // 4047
        MySqlError::ER_OPERATION_NOT_ALLOWED_ON_GR_SECONDARY => "This operation cannot be performed on a Group Replication secondary member, it must be done on the group primary.", // 4048
        MySqlError::ER_GRP_RPL_FAILOVER_CHANNEL_STATUS_PROPAGATION => "Unable to propagate the SOURCE_CONNECTION_AUTO_FAILOVER value for this channel to group replication members. Please retry the operation. ", // 4049
        MySqlError::CR_UNKNOWN_ERROR => "Unknown MySQL error", // 2000
        MySqlError::CR_SOCKET_CREATE_ERROR => "Can't create UNIX socket", // 2001
        MySqlError::CR_CONNECTION_ERROR => "Can't connect to local MySQL server through socket", // 2002
        MySqlError::CR_CONN_HOST_ERROR => "Can't connect to MySQL server", // 2003
        MySqlError::CR_IPSOCK_ERROR => "Can't create TCP/IP socket", // 2004
        MySqlError::CR_UNKNOWN_HOST => "Unknown MySQL server host", // 2005
        MySqlError::CR_SERVER_GONE_ERROR => "MySQL server has gone away", // 2006
        MySqlError::CR_VERSION_ERROR => "Protocol mismatch.", // 2007
        MySqlError::CR_OUT_OF_MEMORY => "MySQL client run out of memory", // 2008
        MySqlError::CR_WRONG_HOST_INFO => "Wrong host info", // 2009
        MySqlError::CR_LOCALHOST_CONNECTION => "Localhost via UNIX socket", // 2010
        MySqlError::CR_TCP_CONNECTION => "Connection via TCP/IP", // 2011
        MySqlError::CR_SERVER_HANDSHAKE_ERR => "Error in server handshake", // 2012
        MySqlError::CR_SERVER_LOST => "Lost connection to MySQL server during query", // 2013
        MySqlError::CR_COMMANDS_OUT_OF_SYNC => "Commands out of sync; you can't run this command now", // 2014
        MySqlError::CR_NAMEDPIPE_CONNECTION => "Connection via named pipe", // 2015
        MySqlError::CR_NAMEDPIPEWAIT_ERROR => "Can't wait for named pipe to host", // 2016
        MySqlError::CR_NAMEDPIPEOPEN_ERROR => "Can't open named pipe to host", // 2017
        MySqlError::CR_NAMEDPIPESETSTATE_ERROR => "Can't set state of named pipe", // 2018
        MySqlError::CR_CANT_READ_CHARSET => "Can't initialize character set", // 2019
        MySqlError::CR_NET_PACKET_TOO_LARGE => "Got packet bigger than 'max_allowed_packet'", // 2020
        MySqlError::CR_EMBEDDED_CONNECTION => "", // 2021
        MySqlError::CR_PROBE_SLAVE_STATUS => "", // 2022
        MySqlError::CR_PROBE_SLAVE_HOSTS => "", // 2023
        MySqlError::CR_PROBE_SLAVE_CONNECT => "", // 2024
        MySqlError::CR_PROBE_MASTER_CONNECT => "", // 2025
        MySqlError::CR_SSL_CONNECTION_ERROR => "SSL connection error", // 2026
        MySqlError::CR_MALFORMED_PACKET => "received malformed packet", // 2027
        MySqlError::CR_WRONG_LICENSE => "Wrong license", // 2028
        MySqlError::CR_NULL_POINTER => "Null pointer", // 2029
        MySqlError::CR_NO_PREPARE_STMT => "Statement is not prepared", // 2030
        MySqlError::CR_PARAMS_NOT_BOUND => "No data supplied for parameters in prepared statement", // 2031
        MySqlError::CR_DATA_TRUNCATED => "Data truncated", // 2032
        MySqlError::CR_NO_PARAMETERS_EXISTS => "No parameters exist", // 2033
        MySqlError::CR_INVALID_PARAMETER_NO => "Invalid parameter number", // 2034
        MySqlError::CR_INVALID_BUFFER_USE => "Invalid buffer type", // 2035
        MySqlError::CR_UNSUPPORTED_PARAM_TYPE => "Buffer type is not supported", // 2036
        MySqlError::CR_SHARED_MEMORY_CONNECTION => "Shared memory connected", // 2037
        MySqlError::CR_SHARED_MEMORY_CONNECT_REQUEST_ERROR => "Shared memory connection failed", // 2038
        MySqlError::CR_SHARED_MEMORY_CONNECT_ANSWER_ERROR => "", // 2039
        MySqlError::CR_SHARED_MEMORY_CONNECT_FILE_MAP_ERROR => "", // 2040
        MySqlError::CR_SHARED_MEMORY_CONNECT_MAP_ERROR => "", // 2041
        MySqlError::CR_SHARED_MEMORY_FILE_MAP_ERROR => "", // 2042
        MySqlError::CR_SHARED_MEMORY_MAP_ERROR => "", // 2043
        MySqlError::CR_SHARED_MEMORY_EVENT_ERROR => "", // 2044
        MySqlError::CR_SHARED_MEMORY_CONNECT_ABANDONED_ERROR => "", // 2045
        MySqlError::CR_SHARED_MEMORY_CONNECT_SET_ERROR => "", // 2046
        MySqlError::CR_CONN_UNKNOW_PROTOCOL => "Wrong or unknown protocol", // 2047
        MySqlError::CR_INVALID_CONN_HANDLE => "Invalid connection handle", // 2048
        MySqlError::CR_SECURE_AUTH => "Connection with old authentication protocol refused.", // 2049
        MySqlError::CR_FETCH_CANCELED => "Fetch cancelled", // 2050
        MySqlError::CR_NO_DATA => "No data", // 2051
        MySqlError::CR_NO_STMT_METADATA => "Prepared statement contains no metadata", // 2052
        MySqlError::CR_NO_RESULT_SET => "No result set", // 2053
        MySqlError::CR_NOT_IMPLEMENTED => "This feature is not implemented or disabled", // 2054
        MySqlError::CR_SERVER_LOST_EXTENDED => "Lost connection to MySQL server", // 2055
        MySqlError::CR_STMT_CLOSED => "Server closed statement due to a prior function call", // 2056
        MySqlError::CR_NEW_STMT_METADATA => "The number of parameters in bound buffers differs from number of columns in resultset", // 2057
        MySqlError::CR_ALREADY_CONNECTED => "Can't connect twice. Already connected", // 2058
        MySqlError::CR_AUTH_PLUGIN_CANNOT_LOAD => "Plugin could not be loaded", // 2059
        MySqlError::CR_DUPLICATE_CONNECTION_ATTR => "An attribute with same name already exists", // 2060
        MySqlError::CR_AUTH_PLUGIN_ERR => "Plugin doesn't support this function", // 2061
        MySqlError::CR_EVENT_CREATE_FAILED => "Creating an event failed", // 5000
        MySqlError::CR_BIND_ADDR_FAILED => "Bind to local interface failed", // 5001
        MySqlError::CR_ASYNC_NOT_SUPPORTED => "Connection type doesn't support asynchronous IO operations", // 5002
        MySqlError::CR_FUNCTION_NOT_SUPPORTED => "Server doesn't support function", // 5003
        MySqlError::CR_FILE_NOT_FOUND => "File not found", // 5004
        MySqlError::CR_FILE_READ => "Error reading file", // 5005
        MySqlError::CR_BULK_WITHOUT_PARAMETERS => "Bulk operation without parameters is not supported", // 5006
        MySqlError::CR_INVALID_STMT => "Invalid statement handle", // 5007
        MySqlError::CR_VERSION_MISMATCH => "Unsupported version", // 5008
    ]; 


    static function desc(int $id)
    {
        return self::$ERROR_DESCRIPTIONS[$id];
    }
}


# vim: set tabstop=4 shiftwidth=4 :
# Local Variables:
# tab-width: 4
# end:
